name: 🐛 Bug Report
description: Report a bug or unexpected behavior in AstroLMS Landing
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us reproduce and fix the issue.
  
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser and version are you using?
      placeholder: "e.g., Chrome 120.0.6099.71, Safari 17.1.2"
    validations:
      required: true
  
  - type: input
    id: device
    attributes:
      label: Device/OS
      description: What device and operating system are you using?
      placeholder: "e.g., iPhone 15 Pro iOS 17.1, Windows 11, macOS Sonoma 14.1"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop files here or paste image URLs...
  
  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: Any console errors or network issues (open browser dev tools > Console)
      placeholder: Paste any console errors here...
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I have tested this on the latest version of the site
          required: true