name: 🚀 Enhancement
description: Suggest improvements to existing features or functionality
title: "[ENHANCEMENT] "
labels: ["enhancement", "improvement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve AstroLMS Landing! Please provide details about the enhancement you'd like to see.
  
  - type: dropdown
    id: area
    attributes:
      label: Enhancement Area
      description: Which area would this enhancement improve?
      options:
        - Performance
        - User Experience (UX)
        - User Interface (UI)
        - Accessibility
        - SEO
        - Mobile Experience
        - Loading Speed
        - Animations
        - Form Functionality
        - Navigation
        - Code Quality
        - Other
    validations:
      required: true
  
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: How does the current feature/functionality work?
      placeholder: Describe how things currently work...
    validations:
      required: true
  
  - type: textarea
    id: proposed-enhancement
    attributes:
      label: Proposed Enhancement
      description: What specific improvements would you like to see?
      placeholder: Describe the enhancement in detail...
    validations:
      required: true
  
  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: How would this enhancement improve the user experience or project?
      placeholder: |
        - Improved user experience because...
        - Better performance due to...
        - Enhanced accessibility by...
        - Increased conversions through...
    validations:
      required: true
  
  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      description: How significant would this enhancement be?
      options:
        - High - Major improvement to core functionality
        - Medium - Noticeable improvement to user experience
        - Low - Minor quality of life improvement
    validations:
      required: true
  
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: |
        - Technical approach suggestions
        - Libraries or tools that might help
        - Design patterns to consider
        - Examples from other sites
  
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples, mockups, or references that illustrate your enhancement idea
      placeholder: Drag and drop files here, paste URLs, or describe examples...
  
  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: What should be considered when implementing this enhancement?
      options:
        - label: Should work across all supported browsers
        - label: Should maintain mobile responsiveness
        - label: Should not break existing functionality
        - label: Should follow existing design patterns
        - label: Should maintain performance standards
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have clearly described the current behavior
          required: true
        - label: I have explained the proposed enhancement and its benefits
          required: true
        - label: I have considered the impact and implementation complexity
          required: true