name: ✨ Feature Request
description: Suggest a new feature or enhancement for AstroLMS Landing
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand what you'd like to see added to AstroLMS Landing.
  
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New UI Component
        - Content Enhancement
        - Performance Improvement
        - Accessibility Improvement
        - SEO Enhancement
        - Animation/Interaction
        - Analytics/Tracking
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - High - Critical for user experience
        - Medium - Would significantly improve experience
        - Low - Nice to have enhancement
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: Clearly describe what you want to happen...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions you've considered...
  
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: How would you and others use this feature?
      placeholder: |
        - As a visitor, I want to...
        - As an investor, I need to...
        - As a team member, I would like to...
    validations:
      required: true
  
  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add any mockups, wireframes, or examples that illustrate your idea
      placeholder: Drag and drop files here or paste image URLs...
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might help us understand your request...
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals and target audience
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true